"""empty message

Revision ID: 551745f7335a
Revises: 93794027389c
Create Date: 2022-10-06 01:09:10.855764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551745f7335a'
down_revision = '93794027389c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Favorites', sa.Column('person_id', sa.Integer(), nullable=True))
    op.add_column('Favorites', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Favorites', 'Person', ['person_id'], ['id'])
    op.create_foreign_key(None, 'Favorites', 'Planet', ['planet_id'], ['id'])
    op.drop_constraint('Person_favorites_id_fkey', 'Person', type_='foreignkey')
    op.drop_column('Person', 'favorites_id')
    op.drop_constraint('Planet_favorites_id_fkey', 'Planet', type_='foreignkey')
    op.drop_column('Planet', 'favorites_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Planet', sa.Column('favorites_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Planet_favorites_id_fkey', 'Planet', 'Favorites', ['favorites_id'], ['id'])
    op.add_column('Person', sa.Column('favorites_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Person_favorites_id_fkey', 'Person', 'Favorites', ['favorites_id'], ['id'])
    op.drop_constraint(None, 'Favorites', type_='foreignkey')
    op.drop_constraint(None, 'Favorites', type_='foreignkey')
    op.drop_column('Favorites', 'planet_id')
    op.drop_column('Favorites', 'person_id')
    # ### end Alembic commands ###
